server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.web: TRACE
    hello: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true